### ISSUE TITLE
关于文献插入方式

### ISSUE THREAD

**Issue by jeanwsr** [NominHanggai/szaboqc#2]
我注意到目前的尾注文献是用endnotes包实现的，是不是可以考虑bibtex或者biblatex呢。
endnotes似乎需要手动输入（不知道有没有程序可以生成），手动也有手动的好处，因为有些尾注并不是标准的文献格式，用bibtex就不方便。
biblatex+endnotes应该可以实现方便的插入，只要`\endnote{\fullcite{xxx}}`即可。缺点是编译时需要使用biber取代默认的bibtex。
不知道有没有更方便的方法。

**Comment by Mulliken** [comment]
当然没问题！我当时为了方便，直接手写了。
________________________________

**Comment by LePingKYXK** [comment]
> 
> 
> 我注意到目前的尾注文献是用endnotes包实现的，是不是可以考虑bibtex或者biblatex呢。
> endnotes似乎需要手动输入（不知道有没有程序可以生成），手动也有手动的好处，因为有些尾注并不是标准的文献格式，用bibtex就不方便。
> biblatex+endnotes应该可以实现方便的插入，只要`\endnote{\fullcite{xxx}}`即可。缺点是编译时需要使用biber取代默认的bibtex。
> 不知道有没有更方便的方法。

从 Sob 的计算化学公社论坛看到这个项目，特地过来。
可以用 EndNote 导出成 `.bib` 文件，方法可以看我的知乎文章 https://zhuanlan.zhihu.com/p/135217810
导出的 style 可以用 `bibTeX Export` ，然后借助 JabRef 软件的 `Generate citation keys` 工具对 `.bib` 文件自动添加添加 keys。
这应该是最方便的转换方法。
希望对此项目有所帮助。

**Comment by hebrewsnabla** [comment]
> 
> 
> > 我注意到目前的尾注文献是用endnotes包实现的，是不是可以考虑bibtex或者biblatex呢。
> > endnotes似乎需要手动输入（不知道有没有程序可以生成），手动也有手动的好处，因为有些尾注并不是标准的文献格式，用bibtex就不方便。
> > biblatex+endnotes应该可以实现方便的插入，只要`\endnote{\fullcite{xxx}}`即可。缺点是编译时需要使用biber取代默认的bibtex。
> > 不知道有没有更方便的方法。
> 
> 从 Sob 的计算化学公社论坛看到这个项目，特地过来。
> 可以用 **EndNote** 导出成 `.bib` 文件，方法可以看我的知乎文章 https://zhuanlan.zhihu.com/p/135217810
> 导出的 style 可以选用 `bibTeX Export` ，然后用 **JabRef** 软件打开 `.bib` 文件，借助 `Generate citation keys` 工具对 `.bib` 文件一次性自动添加添加所有的 keys。
> 这应该是最方便的转换方法。
> 希望对此项目有所帮助。

我们这里讨论的endnotes和文献管理软件EndNote没有关系哈

**Comment by LePingKYXK** [comment]
> 
> 
> > > 我注意到目前的尾注文献是用endnotes包实现的，是不是可以考虑bibtex或者biblatex呢。
> > > endnotes似乎需要手动输入（不知道有没有程序可以生成），手动也有手动的好处，因为有些尾注并不是标准的文献格式，用bibtex就不方便。
> > > biblatex+endnotes应该可以实现方便的插入，只要`\endnote{\fullcite{xxx}}`即可。缺点是编译时需要使用biber取代默认的bibtex。
> > > 不知道有没有更方便的方法。
> > 
> > 
> > 从 Sob 的计算化学公社论坛看到这个项目，特地过来。
> > 可以用 **EndNote** 导出成 `.bib` 文件，方法可以看我的知乎文章 https://zhuanlan.zhihu.com/p/135217810
> > 导出的 style 可以选用 `bibTeX Export` ，然后用 **JabRef** 软件打开 `.bib` 文件，借助 `Generate citation keys` 工具对 `.bib` 文件一次性自动添加添加所有的 keys。
> > 这应该是最方便的转换方法。
> > 希望对此项目有所帮助。
> 
> 我们这里讨论的endnotes和文献管理软件EndNote没有关系哈

啊…… 不好意思，打扰了……
